############################### LOAD GENERATOR CONFIG ##############################
num_tenants = 1
tenant_skew = 0.1
duration = 30

learnable = true
partition = 50
max_out = 32

xloop_factor = 4000
output_factor = 10
xloop_learning_rate = 0.25

############################### LB N/W CONFIG ##############################

[lb]
max_rx_packets = 32
nic_pci = "0000:03:00.1"
num_cores = 8
[lb.server]
rx_queues = 8
ip_addr = "10.10.1.1"
mac_addr = "9c:dc:71:5e:2f:21"

[[compute]]
rx_queues = 8
ip_addr = "10.10.1.5"
mac_addr = "9c:dc:71:49:a8:91"
[[compute]]
rx_queues = 8
ip_addr = "10.10.1.3"
mac_addr = "9c:dc:71:5d:f1:11"
[[compute]]
rx_queues = 8
ip_addr = "10.10.1.4"
mac_addr = "9c:dc:71:5d:e5:31"
[[compute]]
rx_queues = 8
ip_addr = "10.10.1.2"
mac_addr = "9c:dc:71:5c:ef:f1"

[[storage]]
rx_queues = 8
ip_addr = "10.10.1.6"
mac_addr = "9c:dc:71:5d:97:d1"

############################### LB WORKLOAD CONFIG ##############################

[[tables]]
key_len = 30
num_records = 10000
[[tables]]
key_len = 30
num_records = 10000

[[workloads]]
extension = "pushback"
kv = 4
order = 0
table_id = 1
skew = 0.99

[[workloads]]
extension = "pushback"
kv = 0
order = 25600
table_id = 1
skew = 0.99

[[workloads]]
extension = "pushback"
kv = 4
order = 0
table_id = 1
skew = 0.99

[[workloads]]
extension = "pushback"
kv = 0
order = 25600
table_id = 1
skew = 0.99

[[workloads]]
extension = "pushback"
kv = 4
order = 0
table_id = 1
skew = 0.99

[[workloads]]
extension = "pushback"
kv = 0
order = 25600
table_id = 1
skew = 0.99

[[workloads]]
extension = "pushback"
kv = 4
order = 0
table_id = 1
skew = 0.99

[[workloads]]
extension = "pushback"
kv = 0
order = 25600
table_id = 1
skew = 0.99

[[phases]]
ratios = [12.5, 12.5, 12.5, 12.5, 12.5, 12.5, 12.5, 12.5]
