[package]
name = "pushback"
version = "0.1.0"
authors = ["ankitb"]

[lib]
crate-type = ["dylib"]

[dependencies]
db        = { path = "../../db" }
sandstorm = { path = "../../sandstorm" }
cfg-if = "1.0.0"

[features]
default = ["yield"]
yield = []